"""first revision

迁移 ID: f364ac615d92
父迁移:
创建时间: 2025-06-19 16:31:21.961872

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f364ac615d92"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("muicebot-plugin-meme",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "muicebot_plugin_meme_memeorm",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="Emotion ID"
        ),
        sa.Column("path", sa.String(), nullable=False, comment="表情包路径"),
        sa.Column("hash", sa.String(), nullable=False, comment="表情包哈希值"),
        sa.Column("valid", sa.Integer(), nullable=False, comment="表情包是否有效"),
        sa.Column("description", sa.String(), nullable=False, comment="表情包描述"),
        sa.Column("tag", sa.String(), nullable=False, comment="表情包标签"),
        sa.Column("usage", sa.Integer(), nullable=False, comment="表情包使用次数"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_muicebot_plugin_meme_memeorm")),
        info={"bind_key": "muicebot-plugin-meme"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("muicebot_plugin_meme_memeorm")
    # ### end Alembic commands ###
